version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - cd frontend
      - npm install
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'frontend/build'